### ISSUE TITLE
[Question] Conectar com porta serial | Connection with SERIAL port

### ISSUE THREAD

**Issue by cristiano-linvix** [grandchef/escpos-buffer#14]
Olá Francimar, vi que aceita uma grande variedade de impressoras que usamos aqui no Brasil.
Minha dúvida é a seguinte, é possível de utilizar essa library conectando diretamente na porta serial da impressora?
Se sim, tem um exemplo de como fazer?

-- English
Hello Francimar, I saw that you accept a wide variety of printers that we use here in Brazil.
My question is, is it possible to use this library by connecting directly to the printer's serial port?
If so, do you have an example of how to do it?

**Comment by mazinsw** [comment]
Olá Cristiano, sim é possível utilizar conectando direto na porta serial, para isso você deve gerar o buffer para impressão e escrever esse buffer na porta serial, outra forma seria você criar uma conexão serial.

Segue exemplo:
```js
const SerialPort = require('serialport')

const { Printer, Style, Align, Drawer, Model, InMemory } = require('escpos-buffer')

const model = new Model('MP-4200 TH')
const connection = new InMemory()
const printer = new Printer(model, connection)
printer.writeln('Printing for serial port')
printer.feed(6)
printer.buzzer()
printer.cutter()

const port = new SerialPort('COM1')
port.write(connection.buffer())

```

**Comment by cristiano-linvix** [comment]
Thank you!!
