### ISSUE TITLE
Possibility to run into react-native?

### ISSUE THREAD

**Issue by cristiano-linvix** [grandchef/escpos-buffer#37]
Is there a possibility to use it with react native?

Today pngjs and fs libs don't exist in react-native, maybe splitting the core into two libs, one that generates the coding part outside of the imaging part, should work.

What do you think of the idea?

**Comment by mazinsw** [comment]
The PNGJS library is required for printing pictures or unsupported qrcode, fs is required for load PNG files using filename.

A split of theses components allow usage in different platforms, but requires more coding and complexity, its possible an implementation that require version bumping be merged into this project.

Can you implement this and make a pull request?

**Comment by cristiano-linvix** [comment]
I created a repository and started testing it to work.

I'm currently testing on SUNMI devices, I'm having a problem with the format of the sent data.

I have the android native sdk that takes a byte[] to send ESC/POS commands and sends it to the printer, but for some reason it's not working right.

I don't know if I'm doing it wrong.

Would you have time to talk about it?

**Comment by cristiano-linvix** [comment]
About QRCode, in the case of android, we can work with other resources that generate the QRCode in base64 format that the native side should print, but would need to test it first.

**Comment by mazinsw** [comment]
> I created a repository and started testing it to work.
> 
> I'm currently testing on SUNMI devices, I'm having a problem with the format of the sent data.
> 
> I have the android native sdk that takes a byte[] to send ESC/POS commands and sends it to the printer, but for some reason it's not working right.
> 
> I don't know if I'm doing it wrong.
> 
> Would you have time to talk about it?

Maybe SUNMI devices uses different command set for printing, thats why the problems,
if this is the case, creating a new profile will solve the problem.

you can call me at francimar@grandchef.com.br for private conversation

**Comment by TraFost** [comment]
is it possible to run this in react?

**Comment by cristiano-linvix** [comment]
Yes, its possible to run in react.

See the section BROWSER on README.MD
https://github.com/grandchef/escpos-buffer?tab=readme-ov-file#browser

**Comment by cristiano-linvix** [comment]
```typescript
import { Printer, Model, WebUSB } from 'escpos-buffer';

const device = await navigator.usb.requestDevice({
  filters: [
    {
      vendorId: VENDOR_ID,
    },
  ],
});
const connection = new WebUSB(device);
const printer = await Printer.CONNECT('TM-T20', connection);
```

**Comment by TraFost** [comment]
does the first param in **Printer.CONNECT** need to match the printer type?

**Comment by cristiano-linvix** [comment]
Yes, the printer model more specifically.

Many printers currently on the market use the ESC/POS command chain.

Not 100% of the commands will work, but the main ones usually work.

You can learn more in the examples and in the readme file.

**Comment by TraFost** [comment]
thanks for helping me!

**Comment by TraFost** [comment]
is it possible to run with serial port instead of usb request device?

**Comment by cristiano-linvix** [comment]
> is it possible to run with serial port instead of usb request device?

You could take the buffer generated in memory and use some other mechanism to send the data to your serial port.

Note: I'm not sure if the browser communicates directly with the serial port.
