### ISSUE TITLE
Publish new version to NPM

### ISSUE THREAD

**Issue by noisyscanner** [grandchef/escpos-buffer#5]
Is it possible to add a new version to NPM for the new WebUSB stuff?
Maybe this could also be something useful to go into Travis? For example, if you bump the version number it triggers a publish?

**Comment by mazinsw** [comment]
I will try to detect github tag build into travis and add publish script

**Comment by mazinsw** [comment]
Done!

**Comment by noisyscanner** [comment]
Thanks!
