### ISSUE TITLE
Ability to specify height and width greater than double

### ISSUE THREAD

**Issue by noisyscanner** [grandchef/escpos-buffer#7]
Looks like the ESC/POS allows font sizes to go all the way up to 8x:
https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=34
It would be useful to have this functionality.
I am happy to put a PR in to address this - wanted to open this issue to discuss possible solutions.
Perhaps simply, the easy way would be to add to the `Style` enum extra sizes for height and width, but that would probably bloat it out a bit and I'm not sure I am a fan of this solution.
Other ideas:
- A `Height` and `Width` enum - but then we would have to add those to method calls too which isn't ideal
- Add it to the `Font` class - eg `new Font('Font A', Height.Height8, Width.Width6)` or `font.height = Height.Height8` or `printer.font.width = Width.Width6`

**Comment by mazinsw** [comment]
I believe that a property `width` and `height` on Printer will be more useful to apply for a single line, this must also allow keep double height and width style for retrocompatibility.

Ex.:
```javascript
const printer = new Printer(model, connection)
printer.columns = 56
printer.width = 8 // 8x
printer.height = 4 // 4x
printer.write('8x Text')
printer.width = 1 // 1x (back to normal)
printer.height = 1 // 1x (back to normal)

// same as printer.width = 2 and printer.height = 2
printer.writeln('Áçênts R$ 5,00', Style.DoubleWidth | Style.DoubleWidth, Align.Center)
```

**Comment by mazinsw** [comment]
> * Add it to the `Font` class - eg `new Font('Font A', Height.Height8, Width.Width6)` or `font.height = Height.Height8` or `printer.font.width = Width.Width6`

This look well structured, it would be challenging to implement it maintaining the width and height after changing the columns

**Comment by noisyscanner** [comment]
That sounds good - I guess then `Style.DoubleWidth | Style.DoubleHeight` in `printer.writeln` can take precendence over `printer.height` and `printer.width`.
I will try to add a PR for this over the next couple of days.

**Comment by noisyscanner** [comment]
Or maybe, to save having to set and reset values in a very procedural way - what about something like?
```javascript
printer.withStyle({ width: 4, height: 8 }, styledPrinter => {
  styledPrinter.writeln('This is huge');
})
printer.writeln('Normal text size');
```

**Comment by mazinsw** [comment]
> Or maybe, to save having to set and reset values in a very procedural way - what about something like?
> 
> ```js
> printer.withStyle({ width: 4, height: 8 }, styledPrinter => {
>   styledPrinter.writeln('This is huge');
> })
> printer.writeln('Normal text size');
> ```

This way looks better than prior version
